
#pragma once

//
//	Engine Main.h
//  Managing DirectX 11.2 components (the pipeline and the renderers)
//
//  © 2015 Vanity DirectX 11.2 Engine (VXE). Zoraja Consulting d.o.o. All rights reserved.
//

// The code is generated by Visual Studio 2013. 

#include "pch.h"

#include "Common\StepTimer.h"
#include "Common\DeviceResources.h"
#include "Content\RendererBase3D.h"
#include "Content\SampleFpsTextRenderer.h"

// Renders Direct2D and 3D content on the screen.
namespace vxe
{
	class EngineMain : public DX::IDeviceNotify {

	public:
		EngineMain(const std::shared_ptr<DX::DeviceResources>&, const std::shared_ptr<RendererBase3D>&);

		~EngineMain();

		void CreateWindowSizeDependentResources();
		void Update();
		bool Render();

		// IDeviceNotify
		virtual void OnDeviceLost();
		virtual void OnDeviceRestored();

	private:
		// Cached pointer to device resources.
		std::shared_ptr<DX::DeviceResources> m_deviceResources;

		// TODO: Replace with your own content renderers.
		std::shared_ptr<RendererBase3D> m_sceneRenderer;
		std::unique_ptr<SampleFpsTextRenderer> m_fpsTextRenderer;

		// Rendering loop timer.
		DX::StepTimer m_timer;
	};
}